export const CURRENCIES = {
  USDT: "USDT",
  BTC: "BTC",
  ETH: "ETH",
  BNB: "BNB",
}

export const ACTION_TYPES = {
  REQUEST_COINS_FAILED: 'REQUEST_COINS_FAILED',
  FETCH_COINS: 'FETCH_COINS',
  SET_PRICE: 'SET_PRICE',
  SET_CURRENCY: 'SET_CURRENCY',
}

